### ISSUE TITLE
crashes in unhelpful way when run without requirement.txt

### ISSUE THREAD

**Issue by AllenHW** [haipera/haipera#29]
should just add an empty requirement.txt? or explicitly suggest to make a requirements.txt? 

right now it fails with an unhelpful message 
<img width="649" alt="Screenshot 2024-07-20 at 10 53 43 PM" src="https://github.com/user-attachments/assets/1d1263a6-425b-41f8-aa29-ee79afe13c19">

**Comment by tovacinni** [comment]
I think we should automatically create a requirements.txt file (if one doesn't exist) with: https://github.com/bndr/pipreqs

(I haven't gotten around to it but feel free to tackle)

**Comment by AllenHW** [comment]
oh nice, that's a great tool

**Comment by tovacinni** [comment]
addressed by https://github.com/haipera/haipera/pull/37
